### ISSUE TITLE
Should we add "<|endoftext|>" explicitly to the prompt?

### ISSUE THREAD

**Issue by ymoslem** [ai-forever/mgpt#3]
Hello! Thanks for your great efforts.

Should we add "<|endoftext|>" explicitly to the prompt text?

```
prompt_text = "<|endoftext|> " + prompt_text
```

Thanks!

**Comment by TatianaShavrina** [comment]
Hi @ymoslem !

You can add the EOS special token In the end, but why adding it in the beginning? 

When choosing prompts, I would also recommend using "<|endoftext|>" with the actual text ends. If you are working with sentences/short examples, you can join them via "\n"

**Comment by ymoslem** [comment]
Thanks @TatianaShavrina for your response!

I am asking about generation, like we do in [GPT-2](https://huggingface.co/docs/transformers/model_doc/gpt2). Does it make a difference?

**Comment by ymoslem** [comment]
> like we do in GPT-2

I think I found [here](https://beta.openai.com/docs/api-reference/completions) an answer to my original question. It seems that `<|endoftext|>` can be used as a default prompt, i.e. only if there is no other prompt. So, as you said, there is no need to start the text with it during generation.

> I would also recommend using "<|endoftext|>" with the actual text ends

Do you mean adding it to the end of the prompt? Does this apply to generation as well?

Thanks a lot!

**Comment by ymoslem** [comment]
For generation, I completely removed the `<|endoftext|>` and this seems to give the best results.

Thanks for your efforts!
