### ISSUE TITLE
Batch size increase

### ISSUE THREAD

**Issue by edmondja** [ai-forever/mgpt#4]
https://github.com/ai-forever/mgpt/blob/main/notebooks/mgpt_tuning_example.ipynb

Hello, why is batch size = 1 ? Because it does not fit in memory easily ?
Can I increase it by using padding with the tokenizer's padding token ?

**Comment by TatianaShavrina** [comment]
@ollmer what would be your advice?

Also, @edmondja , please specify, do you use the model in colab? Do you fine-tune the model there?

**Comment by ollmer** [comment]
Yes, this is the only batch size that fits into a GPU with 32Gb RAM. The padding token would not help much here. But you can try to decrease the sequence length of each sample if your task allows you to do it. Then you can increase your batch size proportionally to the decrease of seq length.

**Comment by edmondja** [comment]
Ah thanks that’s exactly what I wanted to make sure about.
(Nah I use much better, I use ovh cloud, their notebooks have cheaper V100s, with more RAM by default)
