### ISSUE TITLE
mGPT 13B parameters

### ISSUE THREAD

**Issue by ymoslem** [ai-forever/mgpt#5]
Hello! Impressive work, especially that mGPT might be the only multilingual LM model for text generation so far. The paper mentions that there is another version with 13 billion parameters. I assume its performance will be even better. Is this version available somewhere, even for research purposes? Thank you so much!

**Comment by TatianaShavrina** [comment]
Hey @ymoslem !

We are planning to release it later, by now we are still training it and the loss is still getting smaller. The version of it mentioned in the paper is actually available as an API on the cloud https://sbercloud.ru/ru/datahub/rugpt3family/mgpt-3-13b (very sorry for non-English docs)
