### ISSUE TITLE
add new language to the model? 

### ISSUE THREAD

**Issue by unnir** [ai-forever/mgpt#7]
Hi All, 

Thank you for realising the model. 

I was wondering is it possible to add a support for a new language (Czech) through fine-tuning? 
I mean, I can collect a textual corpora in Czech and finetune the mGPT model for several epochs, do you it can work?

**Comment by TatianaShavrina** [comment]
Hi @unnir,

This is absolutely how it works! We have included slavic languages in the mGPT pretrain data, the tokenizer is also suitable for Czech, so it should be absolutely doable through fine-tuning!

**Comment by unnir** [comment]
Thank you for the quick answer!
